###

POST http://localhost:8080/examples/quarkus/jedi?name=Obi-Wan%20Kenobi&title=Higher%20Ground

###

GET http://localhost:8080/examples/quarkus/jedi/Obi-Wan%20Kenobi

###

POST http://localhost:8080/examples/quarkus/jedi?name=Anakin&title=Not%20A%20Master

###

GET http://localhost:8080/examples/quarkus/jedi/Anakin

###

GET http://localhost:8080/examples/quarkus/jedi/Kirk

###

POST http://localhost:8080/examples/quarkus/jedi?name=Joda&title=Uber Jedi

###

GET http://localhost:8080/examples/quarkus/jedi/Joda

###

DELETE http://localhost:8080/examples/quarkus/jedi/Joda
