GET http://localhost:8080/examples/quarkus/jedi/Obi-Wan

###

GET http://localhost:8080/examples/quarkus/jedi/Anakin

###

GET http://localhost:8080/examples/quarkus/jedi/Kirk

###

POST http://localhost:8080/examples/quarkus/jedi?name=Joda&title=Uber Jedi

###

DELETE http://localhost:8080/examples/quarkus/jedi/Joda
