GET http://localhost:8080/examples/quarkus/plain

###

GET http://localhost:8080/examples/quarkus/jedi/Obi-Wan

###

GET http://localhost:8080/examples/quarkus/jedi/Anakin

###

GET http://localhost:8080/examples/quarkus/jedi/Kirk

###

GET http://localhost:8080/q/health/live

###

GET http://localhost:8080/q/health/ready

###

GET http://localhost:8080/q/health
