database:
  schema: quarkus_service
  host: localhost
  port: 3306

jaeger:
  host: localhost
  port: 14268

redis:
  host: localhost
  port: 6379

quarkus:
  datasource:
    username: ${database.username}
    password: ${database.password}
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://${database.host}:${database.port}/${database.schema}
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
    schemas: ${database.schema}
  hibernate-orm:
    database:
      default-schema: ${database.schema}
  jaeger:
    sampler-type: const
    sampler-param: 1
    # these 2 lines needed to push data to backend, comment to use no-op instead
    service-name: quarkus-micro-service
    endpoint: http://${jaeger.host}:${jaeger.port}/api/traces
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{3.}] (%t) %s%e%n"
  redis:
    hosts: redis://${redis.host}:${redis.port}
  scheduler:
    cron-type: unix

scheduled:
  job1:
    cron: "*/2 * * * *"
  job2:
    cron: "off"
