database:
  schema: quarkus_example
  host: localhost
  port: 3306

quarkus:
  datasource:
    username: ${database.username}
    password: ${database.password}
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://${database.host}:${database.port}/${database.schema}
      driver: com.mysql.cj.jdbc.Driver
  flyway:
    migrate-at-start: true
    schemas: ${database.schema}
  hibernate-orm:
    database:
      default-schema: ${database.schema}
  scheduler:
    cron-type: unix

scheduled:
  job1:
    cron: "*/2 * * * *"
  job2:
    cron: "off"
