database:
  name: ${DB_NAME:quarkus_db}
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:5432}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

jaeger:
  host: localhost
  port: 4317

valkey:
  host: localhost
  port: 6379

quarkus:
  application:
    name: quarkus-micro-service
  datasource:
    username: ${database.username}
    password: ${database.password}
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
      driver: org.postgresql.Driver
  flyway:
    migrate-at-start: true
    schemas: ${database.name}
  hibernate-orm:
    database:
      default-schema: ${database.name}
  otel:
    exporter:
      otlp:
        endpoint: http://${jaeger.host}:${jaeger.port}
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{3.}] (%t) %s%e%n"
  redis:
    hosts: redis://${valkey.host}:${valkey.port}
  scheduler:
    cron-type: unix

scheduled:
  job1:
    cron: "*/2 * * * *"
  job2:
    cron: "off"
