global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: quarkus_scraper
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets: [ 'quarkus-micro-service:8080' ]
