global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus:9090' ]

  # Scrape Quarkus microservice by service name and port inside the Docker Compose network
  - job_name: quarkus_scraper
    scrape_interval: 5s
    metrics_path: /q/metrics
    static_configs:
      - targets: [ 'quarkus-micro-service:8080' ]
        labels:
          app: 'quarkus-micro-service'
          env: 'dev'

# To keep alerting/recording rules:
rule_files:
  - /etc/prometheus/rules/*.yml
