# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - main
      - edge
  pull_request:
    branches:
      - main
      - edge

jobs:
  build:

    runs-on: ubuntu-24.04

    services:
      # This is needed for Testcontainers to detect Docker
      docker:
        image: docker:28.3.0-dind-alpine3.22
        options: --privileged

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      name: Set up JDK 21
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
        cache: 'maven'
    - name: Build with Maven
      run: mvn clean verify -U
    - name: Coverage
      uses: codecov/codecov-action@v5
      with:
        files: ./target/jacoco-report/jacoco.xml
        name: codecov
        token: ${{ secrets.CODECOV_TOKEN }}
